### PR TITLE
Removed vendor/ directory

### PR DESCRIPTION
**Pull request by melinath**
This no longer seems to be a best practice, especially for libraries like terraform-google-conversion.

Related - see discussion on #586.

This is also related to https://github.com/GoogleCloudPlatform/terraform-validator/issues/158 - I wanted to remove vendored files before upgrading to go 1.14.

### CODE REVIEW

**Comment by melinath** [comment]
I am still able to run `make test` locally and have things pass.

**Comment by melinath** [comment]
I'm a little concerned that this could hypothetically cause issues with builds triggered from Magic Modules; I can do a test run of that process after merge to double-check.

**Review by slevenick — APPROVED** [review]
This might require changes in the CI process that builds this, but it sounds like you've got an idea of how to test that!

**Comment by melinath** [comment]
MM still seems to behave as expected with respect to tgc :-)

**Pull request merged**
