### PR TITLE
test: use tf dev override in unit and integration test

### PR DESCRIPTION
**Pull request by iyabchen**
1. Regarding the `go install`. 
If not specify a version like `go install pkg@version`, then it uses go.mod to determine the pkg version, AND all other dependencies will use what is defined in go.mod. 
So the previous error was something like :
- tgc's go.mod has pkgX at version 1, 
- the corresponding tpgb's go.mod has pkgX at version 2,
- 1 > 2 

Not sure whether there is a more concise way to install. In this PR, the way to install is
- using go mod list to find whether a replace mod exist for tpgb (dir field should exist in that case)
  - if it exists, then cd into the dir and run `go install`
  - if not exist, then just use the version to install like `go install tpgb@version`.
- probably due to some dep change, it did not ask for github.com/hashicorp/terraform-plugin-mux to be downloaded first, but it could be a potential issue again if dep of tpgb changes again?   

2. This PR also removed the old terraform binary version copy, so it will only use the base image's go version to test, since dev override can only work on higher version of terraform.

### CODE REVIEW

**Comment by melinath** [comment]
Reassigning to Scott since this has to do with CI behavior and local dev experience.

@iyabchen Could you share step-by-step directions for how to reproduce the various cases you're aware of and any relevant links about go install behavior?

It's weird that go mod tidy doesn't work correctly here. :-/

**Comment by iyabchen** [comment]
> Reassigning to Scott since this has to do with CI behavior and local dev experience.
> 
> @iyabchen Could you share step-by-step directions for how to reproduce the various cases you're aware of and any relevant links about go install behavior?
> 
> It's weird that go mod tidy doesn't work correctly here. :-/

Two test scenarios: 
1. for magic module, where provider version is replaced to a local version
- clone tpgb repo into location X
- run `go mod edit -replace github.com/hashicorp/terraform-provider-google-beta=<tpgb location>`
- run `make test`

2. for presubmit/postsubmit in tgc
- restore the go.mod file to original status (no mod replace in the file)
- run `make test`

The `config-tf-dev-override.sh` file has set -ex, so it should print what it actually installed in the log.

**Review by ScottSuarez — APPROVED** [review]
This makes sense to me.. I do have lingering questions about the integration with magic-module's variants of these commands. Although I presume you're working on it.

**Comment by ScottSuarez** [comment]
https://github.com/GoogleCloudPlatform/magic-modules/blob/0126c3d731f79d8e38905271a8430b3d1676544f/.ci/scripts/go-plus/tgc-tester-integration/test_tgc_integration.sh#L69-L73

https://github.com/GoogleCloudPlatform/magic-modules/blob/0126c3d731f79d8e38905271a8430b3d1676544f/.github/workflows/unit-test-tgc.yml#L45-L55

https://github.com/GoogleCloudPlatform/magic-modules/blob/0126c3d731f79d8e38905271a8430b3d1676544f/.github/workflows/test-tgc.yml#L85-L94

Sorry I mean that the altercation don't break these usecases.

**Comment by ScottSuarez** [comment]
Presumably it works for local replace directives since you look for the DIR in Go list.

**Comment by ScottSuarez** [comment]
Cool, sounds good to me !

**Comment by melinath** [comment]
@ScottSuarez were you able to confirm that the local scenarios worked? Are there any remaining blockers to merging at this point?

**Comment by ScottSuarez** [comment]
I confirmed there were no crashes durring execution in both scenarios and the . I wasn't able to confirm that it's using the providers themselves from the `tf-dev-override.tfrc` file. I'm not sure how to go about testing that. 

From my perspective this is unblocked. I trust that you've validated your scenarios already for your usecase. Please don't consider me a blocker on this.

In particular I like how we are using the make file to wrap this functionality. Thanks for this. I appreciate the implementation design.

**Comment by ScottSuarez** [comment]
As a small note, it's not clear to me if both integration and unit testing need to preform this setup. I suspect that only integration tests need it, but alas I'm a bit limited on the depth of my knowledge here.

**Comment by iyabchen** [comment]
> As a small note, it's not clear to me if both integration and unit testing need to preform this setup. I suspect that only integration tests need it, but alas I'm a bit limited on the depth of my knowledge here.

unit test generates .tfplan.json from .tf files, so will get this override involved.

**Pull request merged**
